# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r: release
cache: packages
sudo: required

after_failure:
  - "cat /home/travis/build/boennecd/survTMB/survTMB.Rcheck/00install.out"
  - "cat /home/travis/build/boennecd/survTMB/survTMB.Rcheck/tests/testthat.Rout"
