# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_VA_funcs <- function(data, parameters) {
    .Call(`_survTMB_get_VA_funcs`, data, parameters)
}

VA_funcs_eval_lb <- function(p, par) {
    .Call(`_survTMB_VA_funcs_eval_lb`, p, par)
}

VA_funcs_eval_grad <- function(p, par) {
    .Call(`_survTMB_VA_funcs_eval_grad`, p, par)
}

