# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_VA_funcs <- function(data, parameters) {
    .Call(`_survTMB_get_VA_funcs`, data, parameters)
}

VA_funcs_eval_lb <- function(p, par) {
    .Call(`_survTMB_VA_funcs_eval_lb`, p, par)
}

VA_funcs_eval_grad <- function(p, par) {
    .Call(`_survTMB_VA_funcs_eval_grad`, p, par)
}

VA_funcs_eval_hess <- function(p, par) {
    .Call(`_survTMB_VA_funcs_eval_hess`, p, par)
}

VA_funcs_eval_hess_sparse <- function(p, par) {
    .Call(`_survTMB_VA_funcs_eval_hess_sparse`, p, par)
}

get_gl_rule <- function(n) {
    .Call(`_survTMB_get_gl_rule`, n)
}

get_commutation <- function(n, m) {
    .Call(`_survTMB_get_commutation`, n, m)
}

joint_start_ll <- function(Y, tstart, tstop, omega, delta, Z, n_nodes, bound_knots, inter_knots, grad) {
    .Call(`_survTMB_joint_start_ll`, Y, tstart, tstop, omega, delta, Z, n_nodes, bound_knots, inter_knots, grad)
}

get_joint_funcs <- function(data, parameters) {
    .Call(`_survTMB_get_joint_funcs`, data, parameters)
}

joint_funcs_eval_lb <- function(p, par) {
    .Call(`_survTMB_joint_funcs_eval_lb`, p, par)
}

joint_funcs_eval_grad <- function(p, par) {
    .Call(`_survTMB_joint_funcs_eval_grad`, p, par)
}

fix_atomic_seqfault <- function() {
    invisible(.Call(`_survTMB_fix_atomic_seqfault`))
}

setup_atomic_cache <- function(n_nodes, type, link = "") {
    invisible(.Call(`_survTMB_setup_atomic_cache`, n_nodes, type, link))
}

